# Generated by Django 4.2.17 on 2025-01-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_post_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Add_Movie',
        ),
    ]
