# Generated by Django 4.2.17 on 2025-01-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
    ]
