# Generated by Django 4.2.17 on 2025-01-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-Title']},
        ),
    ]
