# Generated by Django 4.2.17 on 2025-01-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_comment_options_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['Title']},
        ),
    ]
