# Generated by Django 4.2.17 on 2025-01-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_comment_options_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-Year']},
        ),
    ]
