# Generated by Django 4.2.17 on 2025-01-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AddField(
            model_name='movie',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
