# Generated by Django 4.2.17 on 2025-01-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_rename_slug_movie_slug_remove_movie_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='post',
        ),
    ]
