# Generated by Django 4.2.17 on 2025-01-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_movie_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='ImageURL',
            new_name='imageURL',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='MovieID',
            new_name='movieID',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
    ]
