# Generated by Django 4.2.17 on 2025-01-18 14:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_rename_post_comment_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
