# Generated by Django 4.2.17 on 2025-01-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imageURL',
        ),
    ]
